# Generated by Django 2.2.7 on 2019-12-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Manager',
            new_name='manager',
        ),
    ]
