# Generated by Django 2.2.7 on 2019-12-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191209_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='manager',
            new_name='Manager',
        ),
    ]
